<script setup>
import { computed, onMounted, reactive, ref } from 'vue'
import { useRouter } from 'vue-router'
import { housingApi } from '../../api/housing'
const props = defineProps({ page: { type: String, default: 'dashboard' } })
const router = useRouter()
const houses = ref([])
const appointments = ref([])
const feedbacks = ref([])
const news = ref([])
const message = ref('')
const form = reactive({ id: null, title: '', city: '杭州', district: '', address: '', rentType: 'whole', monthRent: '', area: '', bedroomNum: 1, toiletNum: 1, kitchenNum: 1, livingRoomNum: 1, floor: 1, maxFloor: 10, direction: '南', buildYear: 2020, hasElevator: true, hasAirConditioner: true, description: '', tags: [] })
const stats = computed(() => ({ total: houses.value.length, available: houses.value.filter((item) => item.status === 'available').length, pending: houses.value.filter((item) => item.status === 'pending').length, appointments: appointments.value.length }))
async function load() { [houses.value, appointments.value, feedbacks.value, news.value] = await Promise.all([housingApi.listHouses({}), housingApi.listAppointments(), housingApi.listFeedbacks(), housingApi.listNews()]) }
onMounted(load)
function edit(item) { Object.assign(form, structuredClone(item)); router.push('/admin/houses/form') }
async function updateStatus(id, status) { await housingApi.updateHouseStatus(id, status); await load() }
async function remove(id) { if (confirm('确认删除该房源吗？')) { await housingApi.deleteHouse(id); await load() } }
async function save() { try { form.monthRent = Number(form.monthRent); form.area = Number(form.area); await housingApi.saveHouse(form); router.push('/admin/houses') } catch (error) { message.value = error.message } }
async function resolve(id) { await housingApi.updateFeedbackStatus(id, 'resolved'); await load() }
const pageTitle = computed(() => ({ dashboard: '数据概览', houses: '房源管理', form: form.id ? '编辑房源' : '发布房源', orders: '预约管理', users: '用户管理', news: '资讯管理', feedback: '反馈管理' }[props.page]))
</script>

<template>
  <div class="admin-title"><div><p class="eyebrow">ADMIN CENTER</p><h1>{{ pageTitle }}</h1></div><button v-if="page === 'houses'" class="button primary" @click="Object.assign(form, { id: null, title: '', city: '杭州', district: '', address: '', rentType: 'whole', monthRent: '', area: '', tags: [] }); router.push('/admin/houses/form')">+ 发布房源</button></div>
  <template v-if="page === 'dashboard'"><div class="stat-grid"><div><span>房源总数</span><b>{{ stats.total }}</b><small>当前演示数据</small></div><div><span>可预约房源</span><b>{{ stats.available }}</b><small>已审核并上架</small></div><div><span>待审核房源</span><b>{{ stats.pending }}</b><small>等待平台处理</small></div><div><span>新增预约</span><b>{{ stats.appointments }}</b><small>来自租客提交</small></div></div><div class="admin-card"><div class="card-heading"><h2>最新房源</h2><RouterLink to="/admin/houses" class="text-link">管理房源 →</RouterLink></div><table><thead><tr><th>房源</th><th>月租</th><th>类型</th><th>状态</th></tr></thead><tbody><tr v-for="house in houses.slice(0, 5)" :key="house.id"><td><b>{{ house.title }}</b><small>{{ house.city }} · {{ house.district }}</small></td><td>¥{{ house.monthRent.toLocaleString() }}</td><td>{{ house.rentType === 'whole' ? '整租' : '合租' }}</td><td><span class="status-pill" :class="house.status">{{ { available: '上架中', rented: '已租出', pending: '待审核' }[house.status] }}</span></td></tr></tbody></table></div></template>
  <template v-else-if="page === 'houses'"><div class="admin-card"><table><thead><tr><th>房源</th><th>月租</th><th>类型</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-for="house in houses" :key="house.id"><td><b>{{ house.title }}</b><small>{{ house.city }} · {{ house.address }}</small></td><td>¥{{ house.monthRent.toLocaleString() }}</td><td>{{ house.rentType === 'whole' ? '整租' : '合租' }}</td><td><span class="status-pill" :class="house.status">{{ { available: '上架中', rented: '已租出', pending: '待审核' }[house.status] }}</span></td><td class="actions"><button class="text-link" @click="edit(house)">编辑</button><button v-if="house.status === 'pending'" class="text-link" @click="updateStatus(house.id, 'available')">通过</button><button v-if="house.status === 'available'" class="text-link" @click="updateStatus(house.id, 'rented')">标记租出</button><button class="danger-link" @click="remove(house.id)">删除</button></td></tr></tbody></table></div></template>
  <template v-else-if="page === 'form'"><form class="admin-card house-form" @submit.prevent="save"><div class="form-grid"><label>房源标题<input v-model="form.title" placeholder="例如：西湖边 · 两室一厅整租" /></label><label>城市<select v-model="form.city"><option>杭州</option><option>北京</option><option>上海</option><option>深圳</option></select></label><label>区域<input v-model="form.district" placeholder="例如：西湖区" /></label><label>详细地址<input v-model="form.address" placeholder="例如：文三路 188 号" /></label><label>租住方式<select v-model="form.rentType"><option value="whole">整租</option><option value="share">合租</option></select></label><label>月租金<input v-model="form.monthRent" type="number" min="1" placeholder="单位：元" /></label><label>面积<input v-model="form.area" type="number" min="1" placeholder="单位：平方米" /></label><label>户型<input v-model.number="form.bedroomNum" type="number" min="1" /> 室 <input v-model.number="form.livingRoomNum" type="number" min="0" /> 厅</label><label>楼层<input v-model.number="form.floor" type="number" min="1" /> / <input v-model.number="form.maxFloor" type="number" min="1" /></label><label>朝向<input v-model="form.direction" /></label><label>建成年份<input v-model.number="form.buildYear" type="number" /></label><label>配套<select v-model="form.hasElevator"><option :value="true">有电梯</option><option :value="false">无电梯</option></select></label><label class="full-row">详细介绍<textarea v-model="form.description" rows="5" placeholder="描述房源特点、周边环境等"></textarea></label></div><p v-if="message" class="form-notice">{{ message }}</p><div class="form-actions"><RouterLink to="/admin/houses" class="button ghost">取消</RouterLink><button class="button primary">保存房源</button></div></form></template>
  <template v-else-if="page === 'orders'"><div class="admin-card"><table><thead><tr><th>房源</th><th>预约人</th><th>联系电话</th><th>看房日期</th><th>状态</th></tr></thead><tbody><tr v-if="!appointments.length"><td colspan="5" class="table-empty">暂无预约记录。租客提交预约后会显示在这里。</td></tr><tr v-for="item in appointments" :key="item.id"><td><b>{{ item.houseTitle }}</b></td><td>{{ item.name }}</td><td>{{ item.phone }}</td><td>{{ item.visitDate }}</td><td><span class="status-pill pending">待联系</span></td></tr></tbody></table></div></template>
  <template v-else-if="page === 'users'"><div class="admin-card"><table><thead><tr><th>用户</th><th>角色</th><th>注册时间</th><th>状态</th></tr></thead><tbody><tr><td><b>演示租客</b><small>tenant@example.com</small></td><td>租客</td><td>2026-09-01</td><td><span class="status-pill available">正常</span></td></tr><tr><td><b>平台管理员</b><small>admin@example.com</small></td><td>管理员</td><td>2026-08-20</td><td><span class="status-pill available">正常</span></td></tr></tbody></table></div></template>
  <template v-else-if="page === 'news'"><div class="admin-card"><table><thead><tr><th>资讯标题</th><th>发布时间</th><th>摘要</th><th>操作</th></tr></thead><tbody><tr v-for="item in news" :key="item.id"><td><b>{{ item.title }}</b></td><td>{{ item.publishedAt }}</td><td>{{ item.summary }}</td><td><button class="text-link">编辑</button></td></tr></tbody></table></div></template>
  <template v-else-if="page === 'feedback'"><div class="admin-card"><table><thead><tr><th>用户</th><th>反馈内容</th><th>提交时间</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-for="item in feedbacks" :key="item.id"><td>{{ item.user }}</td><td>{{ item.content }}</td><td>{{ item.createdAt }}</td><td><span class="status-pill" :class="item.status === 'resolved' ? 'available' : 'pending'">{{ item.status === 'resolved' ? '已处理' : '待处理' }}</span></td><td><button v-if="item.status !== 'resolved'" class="text-link" @click="resolve(item.id)">标记已处理</button></td></tr></tbody></table></div></template>
</template>
