<script setup>
import { onMounted, reactive, ref } from 'vue'
import { useRoute } from 'vue-router'
import { housingApi } from '../../api/housing'
const route = useRoute()
const house = ref(null)
const notice = ref('')
const form = reactive({ name: '', phone: '', visitDate: '', note: '' })
onMounted(async () => { house.value = await housingApi.getHouse(route.params.id) })
async function favorite() { await housingApi.toggleFavorite(house.value.id); notice.value = housingApi.isFavorite(house.value.id) ? '已加入收藏' : '已取消收藏' }
async function book() { try { await housingApi.createAppointment({ houseId: house.value.id, houseTitle: house.value.title, ...form }); notice.value = '预约已提交，房东会尽快联系你。'; Object.assign(form, { name: '', phone: '', visitDate: '', note: '' }) } catch (error) { notice.value = error.message } }
</script>

<template>
  <div v-if="house" class="detail-page"><div class="detail-hero" :style="{ background: house.cover }"><div class="page-width detail-hero-content"><RouterLink to="/houses" class="back-link">← 返回房源</RouterLink><span class="type-badge">{{ house.rentType === 'whole' ? '整租' : '合租' }}</span><h1>{{ house.title }}</h1><p>⌖ {{ house.city }} · {{ house.district }} · {{ house.address }}</p></div><span class="detail-symbol">⌂</span></div><div class="page-width detail-layout"><section class="detail-main"><div class="fact-grid"><div><b>{{ house.monthRent.toLocaleString() }}</b><span>元 / 月</span></div><div><b>{{ house.area }}</b><span>平方米</span></div><div><b>{{ house.bedroomNum }} 室 {{ house.livingRoomNum }} 厅</b><span>房屋户型</span></div><div><b>{{ house.floor }}/{{ house.maxFloor }} 层</b><span>所在楼层</span></div></div><article class="detail-block"><h2>房源介绍</h2><p>{{ house.description }}</p><div class="tag-row"><span v-for="tag in house.tags" :key="tag" class="tag">{{ tag }}</span></div></article><article class="detail-block"><h2>房屋信息</h2><dl class="info-list"><div><dt>朝向</dt><dd>{{ house.direction }}</dd></div><div><dt>建成年份</dt><dd>{{ house.buildYear }}</dd></div><div><dt>电梯</dt><dd>{{ house.hasElevator ? '有' : '无' }}</dd></div><div><dt>空调</dt><dd>{{ house.hasAirConditioner ? '有' : '无' }}</dd></div><div><dt>厨房 / 卫生间</dt><dd>{{ house.kitchenNum }} / {{ house.toiletNum }}</dd></div><div><dt>房源状态</dt><dd :class="house.status">{{ house.status === 'available' ? '可预约' : '已租出' }}</dd></div></dl></article><article class="detail-block map-block"><h2>位置</h2><div class="map-placeholder"><span>⌖</span><div><b>{{ house.address }}</b><small>坐标 {{ house.lat }}, {{ house.lng }}</small></div></div></article></section><aside class="booking-card"><button class="favorite-button" :class="{ active: housingApi.isFavorite(house.id) }" @click="favorite">♥ {{ housingApi.isFavorite(house.id) ? '已收藏' : '收藏房源' }}</button><div class="booking-price"><b>¥{{ house.monthRent.toLocaleString() }}</b><span> / 月</span></div><p class="muted">房东：{{ house.landlord.name }} · {{ house.landlord.phone }}</p><template v-if="house.status === 'available'"><h3>预约看房</h3><form class="booking-form" @submit.prevent="book"><input v-model="form.name" placeholder="你的姓名" /><input v-model="form.phone" placeholder="手机号码" /><input v-model="form.visitDate" type="date" /><textarea v-model="form.note" placeholder="补充说明（选填）"></textarea><button class="button primary">提交预约</button></form></template><div v-else class="unavailable">该房源已租出，看看其他房源吧。</div><p v-if="notice" class="form-notice">{{ notice }}</p></aside></div></div>
  <div v-else class="page-width loading">正在加载房源…</div>
</template>
